### ISSUE TITLE
Improvement of language

### ISSUE THREAD

**Issue by ziu1986** [sunnivin/lesson-code-review#1]
There is room to improve the language in the tutorial.

I plan to work through the tutorial pages and suggest changes where things could be formulated in a clearer way.

**Comment by ziu1986** [comment]
> Being able to share more easily (going down the list here)
is *transformative* because it allows projects to scale to a new
level.

@sunnivin: I do not quite understand this sentence. What is meant with a *new level* in this context? I understand whit it is trying to say, though.

**Comment by sunnivin** [comment]
Thank you for the issue @ziu1986 . 

This lesson was made at a point where my schedule was very hectic so there is definitely a lot of potential for improvements. I will also cycle back on the language, but if you find something unclear I'm really happy to have a PR:) 

> > Being able to share more easily (going down the list here)
> > is _transformative_ because it allows projects to scale to a new
> > level.
> 
> @sunnivin: I do not quite understand this sentence. What is meant with a _new level_ in this context? I understand whit it is trying to say, though.

This is a bad copy-and-paste done in a hurry. The point of the episode is to argue for the big list of positive impacts code reviews can do for a project/team.

**Comment by sunnivin** [comment]
Point to improve the workflow:
 If you (@ziu1986,) could write the episode number/file name where you detected an error it would be much faster for me to detect and perform the suggested changes.

**Comment by ziu1986** [comment]
> Point to improve the workflow:
> If you (@ziu1986,) could write the episode number/file name where you detected an error it would be much faster for me to detect and perform the suggested changes.

I will make sure that I'll do this in my PR :-)

**Comment by sunnivin** [comment]
> > Point to improve the workflow:
> > If you (@ziu1986,) could write the episode number/file name where you detected an error it would be much faster for me to detect and perform the suggested changes.
> 
> I will make sure that I'll do this in my PR :-)

And to avoid duplication. Please make sure that you are working on the latest version. I have done some cleaning myself ;)
